### PR TITLE
Increase the timeout when running matlab -e from 10 to 60.

### PR DESCRIPTION
**Pull request by billhoffman**
On the AWS testing machines 10 was not long enough, and it timed
out before it could get the required information which breaks the build.

### CODE REVIEW

**Comment by billhoffman** [comment]
@patmarion @RussTedrake This change is required to get matlab testing working on AWS with Jenkins.  Once this is merged, I will have a PR for the main repo to update the hash to this cmake project.

**Comment by tkoolen** [comment]
Kind of strange that this is necessary, matlab -e completes almost instantaneously on my machine. It doesn't even start matlab, just the script that can also start the matlab application.

**Comment by billhoffman** [comment]
Agreed it is strange.  However, it seems to be needed.  May have something to do with the instance just starting up or a lengthy time to contact a license server.  The bigger question is why there is a timeout at all?  Seems like it should never just hang forever.   The commit that added this timeout said it was to keep it from not working on Windows.  Does this mean you can not get matlab to work on Windows?

**Comment by tkoolen** [comment]
See https://github.com/RobotLocomotion/cmake/pull/21 for the reason. I
guess now that the hang is resolved, we could remove it.

**Pull request merged**
