### PR TITLE
Delete add_matlab_unit_tests.pl.

### PR DESCRIPTION
**Pull request by david-german-tri**
For discussion.  We don't appear to use this in Drake since https://github.com/RobotLocomotion/drake/pull/2097.  Is it in use elsewhere?

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/cmake/39)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@wxmerkt, do you use it in OpenHumanoids?

**Comment by wxmerkt** [comment]
@david-german-tri Thanks for checking. Unfortunately I am not certain about this (it's still referenced in the CTestCustom) - I believe we do not anymore as the tests in the control directory that are tested all appear to be C++-based. Best to ask someone who's worked on it, perhaps @gizatt or @rdeits ?

**Comment by RussTedrake** [comment]
Pretty sure i'm the only one who's used that script and that it's safe to delete

**Comment by RussTedrake** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/cmake/39#-:-KMuQexn4Ld1Xy9hX8XW:676834233)*

**Comment by david-german-tri** [comment]
I don't have permission to merge in this repo.

**Pull request merged**
